runtime: python39 # You can use any runtime, as it's just a placeholder for static files deployment

handlers:
  - url: /static
    static_dir: build/static

  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
